// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: hub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownstreamCommandType int32

const (
	DownstreamCommandType_DOWNSTREAM_COMMAND_TYPE_UNSPECIFIED DownstreamCommandType = 0
	DownstreamCommandType_DOWNSTREAM_COMMAND_TYPE_PLAY        DownstreamCommandType = 1
	DownstreamCommandType_DOWNSTREAM_COMMAND_TYPE_STOP        DownstreamCommandType = 2
)

// Enum value maps for DownstreamCommandType.
var (
	DownstreamCommandType_name = map[int32]string{
		0: "DOWNSTREAM_COMMAND_TYPE_UNSPECIFIED",
		1: "DOWNSTREAM_COMMAND_TYPE_PLAY",
		2: "DOWNSTREAM_COMMAND_TYPE_STOP",
	}
	DownstreamCommandType_value = map[string]int32{
		"DOWNSTREAM_COMMAND_TYPE_UNSPECIFIED": 0,
		"DOWNSTREAM_COMMAND_TYPE_PLAY":        1,
		"DOWNSTREAM_COMMAND_TYPE_STOP":        2,
	}
)

func (x DownstreamCommandType) Enum() *DownstreamCommandType {
	p := new(DownstreamCommandType)
	*p = x
	return p
}

func (x DownstreamCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownstreamCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_proto_enumTypes[0].Descriptor()
}

func (DownstreamCommandType) Type() protoreflect.EnumType {
	return &file_hub_proto_enumTypes[0]
}

func (x DownstreamCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownstreamCommandType.Descriptor instead.
func (DownstreamCommandType) EnumDescriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

type DownstreamMediaFrameType int32

const (
	DownstreamMediaFrameType_DOWNSTREAM_MEDIA_FRAME_TYPE_UNSPECIFIED DownstreamMediaFrameType = 0
	DownstreamMediaFrameType_DOWNSTREAM_MEDIA_FRAME_TYPE_RTP         DownstreamMediaFrameType = 1
	DownstreamMediaFrameType_DOWNSTREAM_MEDIA_FRAME_TYPE_RTCP        DownstreamMediaFrameType = 2
	DownstreamMediaFrameType_DOWNSTREAM_MEDIA_FRAME_TYPE_SDP         DownstreamMediaFrameType = 3
)

// Enum value maps for DownstreamMediaFrameType.
var (
	DownstreamMediaFrameType_name = map[int32]string{
		0: "DOWNSTREAM_MEDIA_FRAME_TYPE_UNSPECIFIED",
		1: "DOWNSTREAM_MEDIA_FRAME_TYPE_RTP",
		2: "DOWNSTREAM_MEDIA_FRAME_TYPE_RTCP",
		3: "DOWNSTREAM_MEDIA_FRAME_TYPE_SDP",
	}
	DownstreamMediaFrameType_value = map[string]int32{
		"DOWNSTREAM_MEDIA_FRAME_TYPE_UNSPECIFIED": 0,
		"DOWNSTREAM_MEDIA_FRAME_TYPE_RTP":         1,
		"DOWNSTREAM_MEDIA_FRAME_TYPE_RTCP":        2,
		"DOWNSTREAM_MEDIA_FRAME_TYPE_SDP":         3,
	}
)

func (x DownstreamMediaFrameType) Enum() *DownstreamMediaFrameType {
	p := new(DownstreamMediaFrameType)
	*p = x
	return p
}

func (x DownstreamMediaFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownstreamMediaFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_proto_enumTypes[1].Descriptor()
}

func (DownstreamMediaFrameType) Type() protoreflect.EnumType {
	return &file_hub_proto_enumTypes[1]
}

func (x DownstreamMediaFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownstreamMediaFrameType.Descriptor instead.
func (DownstreamMediaFrameType) EnumDescriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *StreamId) Reset() {
	*x = StreamId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamId) ProtoMessage() {}

func (x *StreamId) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamId.ProtoReflect.Descriptor instead.
func (*StreamId) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

func (x *StreamId) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StreamId) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type None struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *None) Reset() {
	*x = None{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{2}
}

// What should be done
type DownstreamControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamID string                `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	Command  DownstreamCommandType `protobuf:"varint,2,opt,name=command,proto3,enum=cams.api.hub.DownstreamCommandType" json:"command,omitempty"`
}

func (x *DownstreamControlRequest) Reset() {
	*x = DownstreamControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownstreamControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamControlRequest) ProtoMessage() {}

func (x *DownstreamControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamControlRequest.ProtoReflect.Descriptor instead.
func (*DownstreamControlRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{3}
}

func (x *DownstreamControlRequest) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

func (x *DownstreamControlRequest) GetCommand() DownstreamCommandType {
	if x != nil {
		return x.Command
	}
	return DownstreamCommandType_DOWNSTREAM_COMMAND_TYPE_UNSPECIFIED
}

type DownstreamMediaFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DownstreamMediaFrameType `protobuf:"varint,2,opt,name=type,proto3,enum=cams.api.hub.DownstreamMediaFrameType" json:"type,omitempty"`
	Payload []byte                   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DownstreamMediaFrame) Reset() {
	*x = DownstreamMediaFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownstreamMediaFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamMediaFrame) ProtoMessage() {}

func (x *DownstreamMediaFrame) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamMediaFrame.ProtoReflect.Descriptor instead.
func (*DownstreamMediaFrame) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{4}
}

func (x *DownstreamMediaFrame) GetType() DownstreamMediaFrameType {
	if x != nil {
		return x.Type
	}
	return DownstreamMediaFrameType_DOWNSTREAM_MEDIA_FRAME_TYPE_UNSPECIFIED
}

func (x *DownstreamMediaFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *StreamId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetId() *StreamId {
	if x != nil {
		return x.Id
	}
	return nil
}

type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *StreamId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{6}
}

func (x *PlayRequest) GetId() *StreamId {
	if x != nil {
		return x.Id
	}
	return nil
}

type PauseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *StreamId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{7}
}

func (x *PauseRequest) GetId() *StreamId {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_hub_proto protoreflect.FileDescriptor

var file_hub_proto_rawDesc = []byte{
	0x0a, 0x09, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x6d,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x36, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x22,
	0x75, 0x0a, 0x18, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x3d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x6c, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x3a,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63,
	0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x75, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x35, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6d,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0c, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75,
	0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x84,
	0x01, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x44, 0x4f, 0x57, 0x4e,
	0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x4f, 0x57, 0x4e, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f,
	0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x4f, 0x57, 0x4e, 0x53, 0x54, 0x52, 0x45, 0x41,
	0x4d, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x54, 0x4f, 0x50, 0x10, 0x02, 0x2a, 0xb7, 0x01, 0x0a, 0x18, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x2b, 0x0a, 0x27, 0x44, 0x4f, 0x57, 0x4e, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d,
	0x5f, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x23, 0x0a, 0x1f, 0x44, 0x4f, 0x57, 0x4e, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x4d, 0x45,
	0x44, 0x49, 0x41, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52,
	0x54, 0x50, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x44, 0x4f, 0x57, 0x4e, 0x53, 0x54, 0x52, 0x45,
	0x41, 0x4d, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x52, 0x54, 0x43, 0x50, 0x10, 0x02, 0x12, 0x23, 0x0a, 0x1f, 0x44, 0x4f,
	0x57, 0x4e, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x46,
	0x52, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x44, 0x50, 0x10, 0x03, 0x32,
	0xa4, 0x01, 0x0a, 0x0a, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x4b,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x26, 0x2e,
	0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x49, 0x0a, 0x0b, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x6d,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x12,
	0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x28, 0x01, 0x32, 0x4c, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x72, 0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x32, 0x7c, 0x0a, 0x06, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12, 0x37,
	0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62,
	0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65,
	0x12, 0x1a, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63,
	0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f, 0x6e, 0x65,
	0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hub_proto_rawDescOnce sync.Once
	file_hub_proto_rawDescData = file_hub_proto_rawDesc
)

func file_hub_proto_rawDescGZIP() []byte {
	file_hub_proto_rawDescOnce.Do(func() {
		file_hub_proto_rawDescData = protoimpl.X.CompressGZIP(file_hub_proto_rawDescData)
	})
	return file_hub_proto_rawDescData
}

var file_hub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hub_proto_goTypes = []interface{}{
	(DownstreamCommandType)(0),       // 0: cams.api.hub.DownstreamCommandType
	(DownstreamMediaFrameType)(0),    // 1: cams.api.hub.DownstreamMediaFrameType
	(*Status)(nil),                   // 2: cams.api.hub.Status
	(*StreamId)(nil),                 // 3: cams.api.hub.StreamId
	(*None)(nil),                     // 4: cams.api.hub.None
	(*DownstreamControlRequest)(nil), // 5: cams.api.hub.DownstreamControlRequest
	(*DownstreamMediaFrame)(nil),     // 6: cams.api.hub.DownstreamMediaFrame
	(*RegisterRequest)(nil),          // 7: cams.api.hub.RegisterRequest
	(*PlayRequest)(nil),              // 8: cams.api.hub.PlayRequest
	(*PauseRequest)(nil),             // 9: cams.api.hub.PauseRequest
}
var file_hub_proto_depIdxs = []int32{
	0,  // 0: cams.api.hub.DownstreamControlRequest.command:type_name -> cams.api.hub.DownstreamCommandType
	1,  // 1: cams.api.hub.DownstreamMediaFrame.type:type_name -> cams.api.hub.DownstreamMediaFrameType
	3,  // 2: cams.api.hub.RegisterRequest.id:type_name -> cams.api.hub.StreamId
	3,  // 3: cams.api.hub.PlayRequest.id:type_name -> cams.api.hub.StreamId
	3,  // 4: cams.api.hub.PauseRequest.id:type_name -> cams.api.hub.StreamId
	4,  // 5: cams.api.hub.Downstream.Control:input_type -> cams.api.hub.None
	6,  // 6: cams.api.hub.Downstream.MediaUpload:input_type -> cams.api.hub.DownstreamMediaFrame
	7,  // 7: cams.api.hub.Registrar.Register:input_type -> cams.api.hub.RegisterRequest
	8,  // 8: cams.api.hub.Viewer.Play:input_type -> cams.api.hub.PlayRequest
	9,  // 9: cams.api.hub.Viewer.Pause:input_type -> cams.api.hub.PauseRequest
	5,  // 10: cams.api.hub.Downstream.Control:output_type -> cams.api.hub.DownstreamControlRequest
	4,  // 11: cams.api.hub.Downstream.MediaUpload:output_type -> cams.api.hub.None
	4,  // 12: cams.api.hub.Registrar.Register:output_type -> cams.api.hub.None
	4,  // 13: cams.api.hub.Viewer.Play:output_type -> cams.api.hub.None
	4,  // 14: cams.api.hub.Viewer.Pause:output_type -> cams.api.hub.None
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*None); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownstreamControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownstreamMediaFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PauseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hub_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		EnumInfos:         file_hub_proto_enumTypes,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_rawDesc = nil
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
