// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: viewer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ViewerClient is the client API for Viewer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ViewerClient interface {
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*None, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*None, error)
}

type viewerClient struct {
	cc grpc.ClientConnInterface
}

func NewViewerClient(cc grpc.ClientConnInterface) ViewerClient {
	return &viewerClient{cc}
}

func (c *viewerClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/cams.api.hub.Viewer/Play", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewerClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/cams.api.hub.Viewer/Pause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewerServer is the server API for Viewer service.
// All implementations must embed UnimplementedViewerServer
// for forward compatibility
type ViewerServer interface {
	Play(context.Context, *PlayRequest) (*None, error)
	Pause(context.Context, *PauseRequest) (*None, error)
	mustEmbedUnimplementedViewerServer()
}

// UnimplementedViewerServer must be embedded to have forward compatible implementations.
type UnimplementedViewerServer struct {
}

func (UnimplementedViewerServer) Play(context.Context, *PlayRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedViewerServer) Pause(context.Context, *PauseRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedViewerServer) mustEmbedUnimplementedViewerServer() {}

// UnsafeViewerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewerServer will
// result in compilation errors.
type UnsafeViewerServer interface {
	mustEmbedUnimplementedViewerServer()
}

func RegisterViewerServer(s grpc.ServiceRegistrar, srv ViewerServer) {
	s.RegisterService(&Viewer_ServiceDesc, srv)
}

func _Viewer_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewerServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cams.api.hub.Viewer/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewerServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Viewer_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewerServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cams.api.hub.Viewer/Pause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewerServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Viewer_ServiceDesc is the grpc.ServiceDesc for Viewer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Viewer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cams.api.hub.Viewer",
	HandlerType: (*ViewerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Play",
			Handler:    _Viewer_Play_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Viewer_Pause_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "viewer.proto",
}
