# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: "Install the system dependencies"
          command: |
            sudo apt-get update
      - run:
          name: "Install the Golang dependencies"
          command: |
            sudo apt-get install --assume-yes --no-install-recommends protobuf-compiler protobuf-compiler-grpc
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - run:
          name: "Code generation"
          command: |
            go mod download
            go generate ./...

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
