// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hub.proto
#ifndef GRPC_hub_2eproto__INCLUDED
#define GRPC_hub_2eproto__INCLUDED

#include "hub.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace cams {
namespace api {
namespace hub {

// The service dedicated to the agents
// It is all about producing / uploading media streams
class Downstream final {
 public:
  static constexpr char const* service_full_name() {
    return "cams.api.hub.Downstream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Stream of commands from the server to the client
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> Control(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(ControlRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> AsyncControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(AsyncControlRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> PrepareAsyncControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(PrepareAsyncControlRaw(context, cq));
    }
    // Stream of media frames from the client to the server
    // There should be at most one long-standing call to MediaUpload per agent connected
    // to the cloud.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::cams::api::hub::DownstreamMediaFrame>> MediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::cams::api::hub::DownstreamMediaFrame>>(MediaUploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>> AsyncMediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>>(AsyncMediaUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>> PrepareAsyncMediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>>(PrepareAsyncMediaUploadRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Stream of commands from the server to the client
      virtual void Control(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::cams::api::hub::None,::cams::api::hub::DownstreamControlRequest>* reactor) = 0;
      // Stream of media frames from the client to the server
      // There should be at most one long-standing call to MediaUpload per agent connected
      // to the cloud.
      virtual void MediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::ClientWriteReactor< ::cams::api::hub::DownstreamMediaFrame>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* ControlRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* AsyncControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* PrepareAsyncControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::cams::api::hub::DownstreamMediaFrame>* MediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>* AsyncMediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::cams::api::hub::DownstreamMediaFrame>* PrepareAsyncMediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> Control(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(ControlRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> AsyncControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(AsyncControlRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>> PrepareAsyncControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>>(PrepareAsyncControlRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::cams::api::hub::DownstreamMediaFrame>> MediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::cams::api::hub::DownstreamMediaFrame>>(MediaUploadRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>> AsyncMediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>>(AsyncMediaUploadRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>> PrepareAsyncMediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>>(PrepareAsyncMediaUploadRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Control(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::cams::api::hub::None,::cams::api::hub::DownstreamControlRequest>* reactor) override;
      void MediaUpload(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::ClientWriteReactor< ::cams::api::hub::DownstreamMediaFrame>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* ControlRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* AsyncControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* PrepareAsyncControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::cams::api::hub::DownstreamMediaFrame>* MediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response) override;
    ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>* AsyncMediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::cams::api::hub::DownstreamMediaFrame>* PrepareAsyncMediaUploadRaw(::grpc::ClientContext* context, ::cams::api::hub::None* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Control_;
    const ::grpc::internal::RpcMethod rpcmethod_MediaUpload_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Stream of commands from the server to the client
    virtual ::grpc::Status Control(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* stream);
    // Stream of media frames from the client to the server
    // There should be at most one long-standing call to MediaUpload per agent connected
    // to the cloud.
    virtual ::grpc::Status MediaUpload(::grpc::ServerContext* context, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* reader, ::cams::api::hub::None* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Control() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControl(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_MediaUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MediaUpload() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_MediaUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MediaUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* /*reader*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMediaUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::cams::api::hub::None, ::cams::api::hub::DownstreamMediaFrame>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Control<WithAsyncMethod_MediaUpload<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Control() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Control(context); }));
    }
    ~WithCallbackMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::cams::api::hub::None, ::cams::api::hub::DownstreamControlRequest>* Control(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_MediaUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MediaUpload() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::cams::api::hub::DownstreamMediaFrame, ::cams::api::hub::None>(
            [this](
                   ::grpc::CallbackServerContext* context, ::cams::api::hub::None* response) { return this->MediaUpload(context, response); }));
    }
    ~WithCallbackMethod_MediaUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MediaUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* /*reader*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::cams::api::hub::DownstreamMediaFrame>* MediaUpload(
      ::grpc::CallbackServerContext* /*context*/, ::cams::api::hub::None* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Control<WithCallbackMethod_MediaUpload<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Control() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_MediaUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MediaUpload() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_MediaUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MediaUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* /*reader*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Control() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControl(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_MediaUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MediaUpload() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_MediaUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MediaUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* /*reader*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMediaUpload(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Control() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Control(context); }));
    }
    ~WithRawCallbackMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::cams::api::hub::DownstreamControlRequest, ::cams::api::hub::None>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Control(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MediaUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MediaUpload() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->MediaUpload(context, response); }));
    }
    ~WithRawCallbackMethod_MediaUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MediaUpload(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::cams::api::hub::DownstreamMediaFrame>* /*reader*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* MediaUpload(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

// The service used for authentication and provisioning
class Registrar final {
 public:
  static constexpr char const* service_full_name() {
    return "cams.api.hub.Registrar";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::cams::api::hub::None* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> AsyncRegister(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::cams::api::hub::None* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> AsyncRegister(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) override;
      void Register(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::cams::api::hub::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Register_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Register(::grpc::ServerContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Register() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::cams::api::hub::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::cams::api::hub::None>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Register<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Register() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::RegisterRequest, ::cams::api::hub::None>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cams::api::hub::RegisterRequest* request, ::cams::api::hub::None* response) { return this->Register(context, request, response); }));}
    void SetMessageAllocatorFor_Register(
        ::grpc::MessageAllocator< ::cams::api::hub::RegisterRequest, ::cams::api::hub::None>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::RegisterRequest, ::cams::api::hub::None>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Register(
      ::grpc::CallbackServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Register<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Register() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Register() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Register() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Register(context, request, response); }));
    }
    ~WithRawCallbackMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Register(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Register() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cams::api::hub::RegisterRequest, ::cams::api::hub::None>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cams::api::hub::RegisterRequest, ::cams::api::hub::None>* streamer) {
                       return this->StreamedRegister(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Register(::grpc::ServerContext* /*context*/, const ::cams::api::hub::RegisterRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cams::api::hub::RegisterRequest,::cams::api::hub::None>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Register<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Register<Service > StreamedService;
};

// The service used for authentication and provisioning
class Viewer final {
 public:
  static constexpr char const* service_full_name() {
    return "cams.api.hub.Viewer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::cams::api::hub::None* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> AsyncPlay(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(AsyncPlayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> PrepareAsyncPlay(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(PrepareAsyncPlayRaw(context, request, cq));
    }
    virtual ::grpc::Status Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::cams::api::hub::None* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> AsyncPause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(AsyncPauseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>> PrepareAsyncPause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>>(PrepareAsyncPauseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* AsyncPlayRaw(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* PrepareAsyncPlayRaw(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* AsyncPauseRaw(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cams::api::hub::None>* PrepareAsyncPauseRaw(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::cams::api::hub::None* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> AsyncPlay(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(AsyncPlayRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> PrepareAsyncPlay(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(PrepareAsyncPlayRaw(context, request, cq));
    }
    ::grpc::Status Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::cams::api::hub::None* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> AsyncPause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(AsyncPauseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>> PrepareAsyncPause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>>(PrepareAsyncPauseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) override;
      void Play(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response, std::function<void(::grpc::Status)>) override;
      void Pause(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* AsyncPlayRaw(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* PrepareAsyncPlayRaw(::grpc::ClientContext* context, const ::cams::api::hub::PlayRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* AsyncPauseRaw(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cams::api::hub::None>* PrepareAsyncPauseRaw(::grpc::ClientContext* context, const ::cams::api::hub::PauseRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Play_;
    const ::grpc::internal::RpcMethod rpcmethod_Pause_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Play(::grpc::ServerContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response);
    virtual ::grpc::Status Pause(::grpc::ServerContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Play() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlay(::grpc::ServerContext* context, ::cams::api::hub::PlayRequest* request, ::grpc::ServerAsyncResponseWriter< ::cams::api::hub::None>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Pause() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPause(::grpc::ServerContext* context, ::cams::api::hub::PauseRequest* request, ::grpc::ServerAsyncResponseWriter< ::cams::api::hub::None>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Play<WithAsyncMethod_Pause<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Play() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::PlayRequest, ::cams::api::hub::None>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cams::api::hub::PlayRequest* request, ::cams::api::hub::None* response) { return this->Play(context, request, response); }));}
    void SetMessageAllocatorFor_Play(
        ::grpc::MessageAllocator< ::cams::api::hub::PlayRequest, ::cams::api::hub::None>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::PlayRequest, ::cams::api::hub::None>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Play(
      ::grpc::CallbackServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Pause() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::PauseRequest, ::cams::api::hub::None>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::cams::api::hub::PauseRequest* request, ::cams::api::hub::None* response) { return this->Pause(context, request, response); }));}
    void SetMessageAllocatorFor_Pause(
        ::grpc::MessageAllocator< ::cams::api::hub::PauseRequest, ::cams::api::hub::None>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cams::api::hub::PauseRequest, ::cams::api::hub::None>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Pause(
      ::grpc::CallbackServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Play<WithCallbackMethod_Pause<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Play() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Pause() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Play() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlay(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Pause() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPause(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Play() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Play(context, request, response); }));
    }
    ~WithRawCallbackMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Play(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Pause() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Pause(context, request, response); }));
    }
    ~WithRawCallbackMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Pause(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Play : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Play() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cams::api::hub::PlayRequest, ::cams::api::hub::None>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cams::api::hub::PlayRequest, ::cams::api::hub::None>* streamer) {
                       return this->StreamedPlay(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Play() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Play(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PlayRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlay(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cams::api::hub::PlayRequest,::cams::api::hub::None>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Pause : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Pause() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cams::api::hub::PauseRequest, ::cams::api::hub::None>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cams::api::hub::PauseRequest, ::cams::api::hub::None>* streamer) {
                       return this->StreamedPause(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Pause() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Pause(::grpc::ServerContext* /*context*/, const ::cams::api::hub::PauseRequest* /*request*/, ::cams::api::hub::None* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPause(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cams::api::hub::PauseRequest,::cams::api::hub::None>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Play<WithStreamedUnaryMethod_Pause<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Play<WithStreamedUnaryMethod_Pause<Service > > StreamedService;
};

}  // namespace hub
}  // namespace api
}  // namespace cams


#endif  // GRPC_hub_2eproto__INCLUDED
