// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: controller.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaFrameType int32

const (
	MediaFrameType_FrameType_UNSPECIFIED MediaFrameType = 0
	MediaFrameType_FrameType_RTP         MediaFrameType = 1
	MediaFrameType_FrameType_RTCP        MediaFrameType = 2
)

// Enum value maps for MediaFrameType.
var (
	MediaFrameType_name = map[int32]string{
		0: "FrameType_UNSPECIFIED",
		1: "FrameType_RTP",
		2: "FrameType_RTCP",
	}
	MediaFrameType_value = map[string]int32{
		"FrameType_UNSPECIFIED": 0,
		"FrameType_RTP":         1,
		"FrameType_RTCP":        2,
	}
)

func (x MediaFrameType) Enum() *MediaFrameType {
	p := new(MediaFrameType)
	*p = x
	return p
}

func (x MediaFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_proto_enumTypes[0].Descriptor()
}

func (MediaFrameType) Type() protoreflect.EnumType {
	return &file_controller_proto_enumTypes[0]
}

func (x MediaFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaFrameType.Descriptor instead.
func (MediaFrameType) EnumDescriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

type ControlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Playing *RtspPlayNotify `protobuf:"bytes,1,opt,name=playing,proto3" json:"playing,omitempty"`
}

func (x *ControlReply) Reset() {
	*x = ControlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReply) ProtoMessage() {}

func (x *ControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReply.ProtoReflect.Descriptor instead.
func (*ControlReply) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ControlReply) GetPlaying() *RtspPlayNotify {
	if x != nil {
		return x.Playing
	}
	return nil
}

type ControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Play     *RtspPlay     `protobuf:"bytes,1,opt,name=play,proto3" json:"play,omitempty"`
	Pause    *RtspPause    `protobuf:"bytes,2,opt,name=pause,proto3" json:"pause,omitempty"`
	Teardown *RtspTeardown `protobuf:"bytes,3,opt,name=teardown,proto3" json:"teardown,omitempty"`
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ControlRequest) GetPlay() *RtspPlay {
	if x != nil {
		return x.Play
	}
	return nil
}

func (x *ControlRequest) GetPause() *RtspPause {
	if x != nil {
		return x.Pause
	}
	return nil
}

func (x *ControlRequest) GetTeardown() *RtspTeardown {
	if x != nil {
		return x.Teardown
	}
	return nil
}

type RtspPlayNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamID string `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
}

func (x *RtspPlayNotify) Reset() {
	*x = RtspPlayNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtspPlayNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtspPlayNotify) ProtoMessage() {}

func (x *RtspPlayNotify) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtspPlayNotify.ProtoReflect.Descriptor instead.
func (*RtspPlayNotify) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *RtspPlayNotify) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

type RtspPlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamID string `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
}

func (x *RtspPlay) Reset() {
	*x = RtspPlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtspPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtspPlay) ProtoMessage() {}

func (x *RtspPlay) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtspPlay.ProtoReflect.Descriptor instead.
func (*RtspPlay) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *RtspPlay) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

type RtspPause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamID string `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
}

func (x *RtspPause) Reset() {
	*x = RtspPause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtspPause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtspPause) ProtoMessage() {}

func (x *RtspPause) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtspPause.ProtoReflect.Descriptor instead.
func (*RtspPause) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *RtspPause) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

type RtspTeardown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamID string `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
}

func (x *RtspTeardown) Reset() {
	*x = RtspTeardown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RtspTeardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtspTeardown) ProtoMessage() {}

func (x *RtspTeardown) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtspTeardown.ProtoReflect.Descriptor instead.
func (*RtspTeardown) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

func (x *RtspTeardown) GetStreamID() string {
	if x != nil {
		return x.StreamID
	}
	return ""
}

type MediaFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *StreamId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    MediaFrameType `protobuf:"varint,2,opt,name=type,proto3,enum=cams.api.hub.MediaFrameType" json:"type,omitempty"`
	Payload []byte         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *MediaFrame) Reset() {
	*x = MediaFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFrame) ProtoMessage() {}

func (x *MediaFrame) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFrame.ProtoReflect.Descriptor instead.
func (*MediaFrame) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{6}
}

func (x *MediaFrame) GetId() *StreamId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MediaFrame) GetType() MediaFrameType {
	if x != nil {
		return x.Type
	}
	return MediaFrameType_FrameType_UNSPECIFIED
}

func (x *MediaFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_controller_proto protoreflect.FileDescriptor

var file_controller_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62,
	0x1a, 0x09, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0c, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63,
	0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x52, 0x74, 0x73, 0x70,
	0x50, 0x6c, 0x61, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x69, 0x6e, 0x67, 0x22, 0xa3, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x68, 0x75, 0x62, 0x2e, 0x52, 0x74, 0x73, 0x70, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x04, 0x70, 0x6c,
	0x61, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62,
	0x2e, 0x52, 0x74, 0x73, 0x70, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x05, 0x70, 0x61, 0x75, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x75, 0x62, 0x2e, 0x52, 0x74, 0x73, 0x70, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x52,
	0x08, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x22, 0x2c, 0x0a, 0x0e, 0x52, 0x74, 0x73,
	0x70, 0x50, 0x6c, 0x61, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x08, 0x52, 0x74, 0x73, 0x70, 0x50,
	0x6c, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22,
	0x27, 0x0a, 0x09, 0x52, 0x74, 0x73, 0x70, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x74, 0x73, 0x70,
	0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x49, 0x44, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x61, 0x6d, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x52, 0x0a, 0x0e, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x52, 0x54, 0x50, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x54, 0x43, 0x50, 0x10, 0x02, 0x32, 0x98, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x1a, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x75, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x68, 0x75, 0x62, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x12,
	0x2e, 0x63, 0x61, 0x6d, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x75, 0x62, 0x2e, 0x4e, 0x6f,
	0x6e, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData = file_controller_proto_rawDesc
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_proto_rawDescData)
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_controller_proto_goTypes = []interface{}{
	(MediaFrameType)(0),    // 0: cams.api.hub.MediaFrameType
	(*ControlReply)(nil),   // 1: cams.api.hub.ControlReply
	(*ControlRequest)(nil), // 2: cams.api.hub.ControlRequest
	(*RtspPlayNotify)(nil), // 3: cams.api.hub.RtspPlayNotify
	(*RtspPlay)(nil),       // 4: cams.api.hub.RtspPlay
	(*RtspPause)(nil),      // 5: cams.api.hub.RtspPause
	(*RtspTeardown)(nil),   // 6: cams.api.hub.RtspTeardown
	(*MediaFrame)(nil),     // 7: cams.api.hub.MediaFrame
	(*StreamId)(nil),       // 8: cams.api.hub.StreamId
	(*None)(nil),           // 9: cams.api.hub.None
}
var file_controller_proto_depIdxs = []int32{
	3, // 0: cams.api.hub.ControlReply.playing:type_name -> cams.api.hub.RtspPlayNotify
	4, // 1: cams.api.hub.ControlRequest.play:type_name -> cams.api.hub.RtspPlay
	5, // 2: cams.api.hub.ControlRequest.pause:type_name -> cams.api.hub.RtspPause
	6, // 3: cams.api.hub.ControlRequest.teardown:type_name -> cams.api.hub.RtspTeardown
	8, // 4: cams.api.hub.MediaFrame.id:type_name -> cams.api.hub.StreamId
	0, // 5: cams.api.hub.MediaFrame.type:type_name -> cams.api.hub.MediaFrameType
	1, // 6: cams.api.hub.Controller.Control:input_type -> cams.api.hub.ControlReply
	7, // 7: cams.api.hub.Controller.MediaUpload:input_type -> cams.api.hub.MediaFrame
	2, // 8: cams.api.hub.Controller.Control:output_type -> cams.api.hub.ControlRequest
	9, // 9: cams.api.hub.Controller.MediaUpload:output_type -> cams.api.hub.None
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	file_hub_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtspPlayNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtspPlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtspPause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RtspTeardown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		EnumInfos:         file_controller_proto_enumTypes,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_rawDesc = nil
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
